apiVersion: apps/v1
kind: Deployment # {insert kind here}
metadata:
  labels:
    run: djangoserver
  name: djangoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: djangoserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: djangoserver
    spec:
      containers:
      - image: us.icr.io/$MY_NAMESPACE/djangoserver:1 # {insert image here}
        imagePullPolicy: Always
        name: djangoserver
        ports:
        - containerPort: 8000 # {insert port here}
          protocol: TCP
      restartPolicy: Always
